// MIR Walkthrough - Generated by stable-mir-json

#set document(title: "MIR Walkthrough")
#set page(margin: 2cm, numbering: "1")
#set text(font: "New Computer Modern", size: 10pt)
#set heading(numbering: "1.1")
#set par(justify: true)

#show raw.where(block: true): block.with(
  fill: luma(245),
  inset: 8pt,
  radius: 4pt,
  width: 100%,
)

#show table.cell.where(y: 0): strong

= `main` — MIR Walkthrough

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  *Purpose:* #text(fill: rgb("#999999"))[TODO: Describe why this walkthrough exists]
]

== Source Context

```rust
fn main() {
    let a = Letter::A;
}
```

== Function Overview

- *Function:* `main`
- *Basic blocks:* 1
- *Return type:* `()`

== Locals

#table(
  columns: (auto, 1fr, auto),
  align: (center, left, left),
  [*Local*], [*Type*], [*Notes*],
  [`0`], [`()`], [Return place],
  [`1`], [`Letter`], [],
)

== Control-Flow Overview

#box(width: 150pt, height: 54pt, {
  place(dx: 70pt, dy: 10pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#e8f5e9"),
    stroke: (paint: rgb("#4caf50"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb0]),
  ))
})

== Basic Blocks

=== bb0 #text(fill: rgb("#888888"), weight: "regular")[ — entry]

_Entry point of the function._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_1 = Letter::A()`], [Construct aggregate],
  [`→ return`], [Return from function],
)

== Key Observations

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  #text(fill: rgb("#999999"))[TODO: Add bullet points summarizing what this MIR teaches]
  
  - 
  - 
]

== Takeaways

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  #text(fill: rgb("#999999"))[TODO: One or two sentences to generalize this example]
]

#pagebreak()

