// MIR Walkthrough - Generated by stable-mir-json

#set document(title: "MIR Walkthrough")
#set page(margin: 2cm, numbering: "1")
#set text(font: "New Computer Modern", size: 10pt)
#set heading(numbering: "1.1")
#set par(justify: true)

#show raw.where(block: true): block.with(
  fill: luma(245),
  inset: 8pt,
  radius: 4pt,
  width: 100%,
)

#show table.cell.where(y: 0): strong

= `main` — MIR Walkthrough

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  *Purpose:* #text(fill: rgb("#999999"))[TODO: Describe why this walkthrough exists]
]

== Source Context

```rust
fn main() {
    let ans = fibonacci(5);

    assert!(ans == 5);
}
```

== Function Overview

- *Function:* `main`
- *Basic blocks:* 4
- *Return type:* `()`
- *Notable properties:*
  - Contains panic path
  - Has conditional branches

== Locals

#table(
  columns: (auto, 1fr, auto),
  align: (center, left, left),
  [*Local*], [*Type*], [*Notes*],
  [`0`], [`()`], [Return place],
  [`1`], [`u32`], [],
  [`2`], [`!`], [],
)

== Control-Flow Overview

#box(width: 230pt, height: 154pt, {
  place(dx: 100pt, dy: 34pt, line(
    start: (0pt, 0pt), end: (0pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 96pt, dy: 54pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 84pt, line(
    start: (0pt, 0pt), end: (-40pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 56pt, dy: 104pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 84pt, line(
    start: (0pt, 0pt), end: (80pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 176pt, dy: 104pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 70pt, dy: 10pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#e8f5e9"),
    stroke: (paint: rgb("#4caf50"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb0]),
  ))
  place(dx: 70pt, dy: 60pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#f3e5f5"),
    stroke: (paint: rgb("#9c27b0"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb1]),
  ))
  place(dx: 30pt, dy: 110pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#e3f2fd"),
    stroke: (paint: rgb("#2196f3"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb2]),
  ))
  place(dx: 150pt, dy: 110pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#ffebee"),
    stroke: (paint: rgb("#f44336"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb3]),
  ))
})

== Basic Blocks

=== bb0 #text(fill: rgb("#888888"), weight: "regular")[ — entry]

_Entry point of the function._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ \_1 = fibonacci(5) → bb1`], [Call fibonacci],
)

=== bb1 #text(fill: rgb("#888888"), weight: "regular")[ — branch point]

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ switch(\_1) \[5→bb2; else→bb3\]`], [Branch on \_1],
)

=== bb2 #text(fill: rgb("#888888"), weight: "regular")[ — return / success]

_Normal return path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ return`], [Return from function],
)

=== bb3 #text(fill: rgb("#888888"), weight: "regular")[ — panic path]

_Panic/diverging path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ \_2 = panic(\[16 bytes\])`], [Call panic],
)

== Key Observations

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  #text(fill: rgb("#999999"))[TODO: Add bullet points summarizing what this MIR teaches]
  
  - 
  - 
]

== Takeaways

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  #text(fill: rgb("#999999"))[TODO: One or two sentences to generalize this example]
]

#pagebreak()

= `fibonacci` — MIR Walkthrough

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  *Purpose:* #text(fill: rgb("#999999"))[TODO: Describe why this walkthrough exists]
]

== Source Context

```rust
fn fibonacci(n:u32) -> u32 {
    match n {
        0 => 0,
        1 => 1,
        _ => fibonacci(n - 2) + fibonacci(n - 1),
    }
}
```

== Function Overview

- *Function:* `fibonacci`
- *Basic blocks:* 10
- *Return type:* `u32`
- *Notable properties:*
  - Contains panic path
  - Uses checked arithmetic
  - Recursive
  - Contains assertions
  - Has conditional branches

== Locals

#table(
  columns: (auto, 1fr, auto),
  align: (center, left, left),
  [*Local*], [*Type*], [*Notes*],
  [`0`], [`u32`], [Return place],
  [`1`], [`u32`], [],
  [`2`], [`u32`], [],
  [`3`], [`u32`], [],
  [`4`], [`(u32, bool)`], [],
  [`5`], [`u32`], [],
  [`6`], [`u32`], [],
  [`7`], [`(u32, bool)`], [],
  [`8`], [`(u32, bool)`], [],
)

== Control-Flow Overview

#box(width: 250pt, height: 354pt, {
  place(dx: 100pt, dy: 34pt, line(
    start: (0pt, 0pt), end: (100pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 196pt, dy: 54pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 34pt, line(
    start: (0pt, 0pt), end: (20pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 116pt, dy: 54pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 34pt, line(
    start: (0pt, 0pt), end: (-60pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 36pt, dy: 54pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 40pt, dy: 84pt, line(
    start: (0pt, 0pt), end: (20pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 56pt, dy: 104pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 120pt, dy: 84pt, line(
    start: (0pt, 0pt), end: (20pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 136pt, dy: 104pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 200pt, dy: 84pt, line(
    start: (0pt, 0pt), end: (-60pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 136pt, dy: 104pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 60pt, dy: 134pt, line(
    start: (0pt, 0pt), end: (40pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 96pt, dy: 154pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 184pt, line(
    start: (0pt, 0pt), end: (0pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 96pt, dy: 204pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 234pt, line(
    start: (0pt, 0pt), end: (0pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 96pt, dy: 254pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 284pt, line(
    start: (0pt, 0pt), end: (0pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 96pt, dy: 304pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 334pt, line(
    start: (0pt, 0pt), end: (40pt, -224pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 136pt, dy: 104pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 70pt, dy: 10pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#e8f5e9"),
    stroke: (paint: rgb("#4caf50"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb0]),
  ))
  place(dx: 10pt, dy: 60pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#fafafa"),
    stroke: (paint: rgb("#9e9e9e"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb1]),
  ))
  place(dx: 90pt, dy: 60pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#fafafa"),
    stroke: (paint: rgb("#9e9e9e"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb2]),
  ))
  place(dx: 170pt, dy: 60pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#fafafa"),
    stroke: (paint: rgb("#9e9e9e"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb3]),
  ))
  place(dx: 30pt, dy: 110pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#fafafa"),
    stroke: (paint: rgb("#9e9e9e"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb4]),
  ))
  place(dx: 70pt, dy: 160pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#fafafa"),
    stroke: (paint: rgb("#9e9e9e"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb5]),
  ))
  place(dx: 70pt, dy: 210pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#fafafa"),
    stroke: (paint: rgb("#9e9e9e"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb6]),
  ))
  place(dx: 70pt, dy: 260pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#fafafa"),
    stroke: (paint: rgb("#9e9e9e"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb7]),
  ))
  place(dx: 70pt, dy: 310pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#fafafa"),
    stroke: (paint: rgb("#9e9e9e"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb8]),
  ))
  place(dx: 110pt, dy: 110pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#e3f2fd"),
    stroke: (paint: rgb("#2196f3"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb9]),
  ))
})

== Basic Blocks

=== bb0 #text(fill: rgb("#888888"), weight: "regular")[ — entry]

_Entry point of the function._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ switch(\_1) \[0→bb3, 1→bb2; else→bb1\]`], [Branch on \_1],
)

=== bb1

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_4 = checked(\_1 - 2)`], [Checked Subtract (may panic)],
  [`→ assert(move \_4.1 == false) → bb4`], [Panic if move \_4.1 is true],
)

=== bb2

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_0 = 1`], [Load constant],
  [`→ goto bb9`], [Jump to bb9],
)

=== bb3

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_0 = 0`], [Load constant],
  [`→ goto bb9`], [Jump to bb9],
)

=== bb4

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_3 = move \_4.0`], [Move value],
  [`→ \_2 = fibonacci(move \_3) → bb5`], [Recursive call to fibonacci],
)

=== bb5

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_7 = checked(\_1 - 1)`], [Checked Subtract (may panic)],
  [`→ assert(move \_7.1 == false) → bb6`], [Panic if move \_7.1 is true],
)

=== bb6

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_6 = move \_7.0`], [Move value],
  [`→ \_5 = fibonacci(move \_6) → bb7`], [Recursive call to fibonacci],
)

=== bb7

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_8 = checked(\_2 + \_5)`], [Checked Add (may panic)],
  [`→ assert(move \_8.1 == false) → bb8`], [Panic if move \_8.1 is true],
)

=== bb8

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_0 = move \_8.0`], [Move value],
  [`→ goto bb9`], [Jump to bb9],
)

=== bb9 #text(fill: rgb("#888888"), weight: "regular")[ — return / success]

_Normal return path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ return`], [Return from function],
)

== Key Observations

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  #text(fill: rgb("#999999"))[TODO: Add bullet points summarizing what this MIR teaches]
  
  - 
  - 
]

== Takeaways

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  #text(fill: rgb("#999999"))[TODO: One or two sentences to generalize this example]
]

#pagebreak()

