// MIR Walkthrough - Generated by stable-mir-json

#set document(title: "MIR Walkthrough")
#set page(margin: 2cm, numbering: "1")
#set text(font: "New Computer Modern", size: 10pt)
#set heading(numbering: "1.1")
#set par(justify: true)

#show raw.where(block: true): block.with(
  fill: luma(245),
  inset: 8pt,
  radius: 4pt,
  width: 100%,
)

#show table.cell.where(y: 0): strong

= `main` — MIR Walkthrough

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  *Purpose:* #text(fill: rgb("#999999"))[TODO: Describe why this walkthrough exists]
]

== Source Context

```rust
fn main() {
    let a: WithParam<u32> = WithParam{the_t: 42, another: 42};

    let b: WithParam<u64> = WithParam{the_t: 42, another: 42};

    let c: Result<u8, usize> = Err(a.another);
    let d : Result<u64, u8> = Ok(b.the_t);

    let x = c.err().unwrap();

    assert!(x as u64 == d.unwrap());
}
```

== Function Overview

- *Function:* `main`
- *Basic blocks:* 6
- *Return type:* `()`
- *Notable properties:*
  - Contains panic path
  - Has conditional branches

== Locals

#table(
  columns: (auto, 1fr, auto),
  align: (center, left, left),
  [*Local*], [*Type*], [*Notes*],
  [`0`], [`()`], [Return place],
  [`1`], [`WithParam\<u32\>`], [],
  [`2`], [`WithParam\<u64\>`], [],
  [`3`], [`std::result::Result\<u8, usize\>`], [],
  [`4`], [`usize`], [],
  [`5`], [`std::result::Result\<u64, u8\>`], [],
  [`6`], [`u64`], [],
  [`7`], [`usize`], [],
  [`8`], [`std::option::Option\<usize\>`], [],
  [`9`], [`bool`], [],
  [`10`], [`u64`], [],
  [`11`], [`u64`], [],
  [`12`], [`!`], [],
)

== Control-Flow Overview

#box(width: 230pt, height: 254pt, {
  place(dx: 100pt, dy: 34pt, line(
    start: (0pt, 0pt), end: (0pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 96pt, dy: 54pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 84pt, line(
    start: (0pt, 0pt), end: (0pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 96pt, dy: 104pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 134pt, line(
    start: (0pt, 0pt), end: (0pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 96pt, dy: 154pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 184pt, line(
    start: (0pt, 0pt), end: (80pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 176pt, dy: 204pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 184pt, line(
    start: (0pt, 0pt), end: (-40pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 56pt, dy: 204pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 70pt, dy: 10pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#e8f5e9"),
    stroke: (paint: rgb("#4caf50"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb0]),
  ))
  place(dx: 70pt, dy: 60pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#fafafa"),
    stroke: (paint: rgb("#9e9e9e"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb1]),
  ))
  place(dx: 70pt, dy: 110pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#fafafa"),
    stroke: (paint: rgb("#9e9e9e"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb2]),
  ))
  place(dx: 70pt, dy: 160pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#f3e5f5"),
    stroke: (paint: rgb("#9c27b0"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb3]),
  ))
  place(dx: 30pt, dy: 210pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#e3f2fd"),
    stroke: (paint: rgb("#2196f3"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb4]),
  ))
  place(dx: 150pt, dy: 210pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#ffebee"),
    stroke: (paint: rgb("#f44336"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb5]),
  ))
})

== Basic Blocks

=== bb0 #text(fill: rgb("#888888"), weight: "regular")[ — entry]

_Entry point of the function._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_1 = WithParam(42, 42)`], [Construct aggregate],
  [`\_2 = WithParam(42, 42)`], [Construct aggregate],
  [`\_4 = \_1.1`], [Copy value],
  [`\_3 = Result::Err(move \_4)`], [Construct aggregate],
  [`\_6 = \_2.0`], [Copy value],
  [`\_5 = Result::Ok(move \_6)`], [Construct aggregate],
  [`→ \_8 = err(\_3) → bb1`], [Call err],
)

=== bb1

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ \_7 = unwrap(move \_8) → bb2`], [Call unwrap],
)

=== bb2

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_10 = \_7 as RigidTy(Uint(U64))`], [Integer conversion],
  [`→ \_11 = unwrap(\_5) → bb3`], [Call unwrap],
)

=== bb3 #text(fill: rgb("#888888"), weight: "regular")[ — branch point]

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_9 = move \_10 == move \_11`], [Equal operation],
  [`→ switch(move \_9) \[0→bb5; else→bb4\]`], [Branch on move \_9],
)

=== bb4 #text(fill: rgb("#888888"), weight: "regular")[ — return / success]

_Normal return path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ return`], [Return from function],
)

=== bb5 #text(fill: rgb("#888888"), weight: "regular")[ — panic path]

_Panic/diverging path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ \_12 = panic(\[16 bytes\])`], [Call panic],
)

== Key Observations

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  #text(fill: rgb("#999999"))[TODO: Add bullet points summarizing what this MIR teaches]
  
  - 
  - 
]

== Takeaways

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  #text(fill: rgb("#999999"))[TODO: One or two sentences to generalize this example]
]

#pagebreak()

