// MIR Walkthrough - Generated by stable-mir-json

#set document(title: "MIR Walkthrough")
#set page(margin: 2cm, numbering: "1")
#set text(font: "New Computer Modern", size: 10pt)
#set heading(numbering: "1.1")
#set par(justify: true)

#show raw.where(block: true): block.with(
  fill: luma(245),
  inset: 8pt,
  radius: 4pt,
  width: 100%,
)

#show table.cell.where(y: 0): strong

= `main` — MIR Walkthrough

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  *Purpose:* #text(fill: rgb("#999999"))[TODO: Describe why this walkthrough exists]
]

== Source Context

```rust
    let b:u32 = 4294967294 + 1;
    assert!(a == b)
}
```

== Function Overview

- *Function:* `main`
- *Basic blocks:* 4
- *Return type:* `()`
- *Notable properties:*
  - Contains panic path
  - Uses checked arithmetic
  - Contains assertions
  - Has conditional branches

== Locals

#table(
  columns: (auto, 1fr, auto),
  align: (center, left, left),
  [*Local*], [*Type*], [*Notes*],
  [`0`], [`()`], [Return place],
  [`1`], [`u32`], [],
  [`2`], [`(u32, bool)`], [],
  [`3`], [`bool`], [],
  [`4`], [`u32`], [],
  [`5`], [`!`], [],
)

== Control-Flow Overview

#box(width: 230pt, height: 154pt, {
  place(dx: 100pt, dy: 34pt, line(
    start: (0pt, 0pt), end: (0pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 96pt, dy: 54pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 84pt, line(
    start: (0pt, 0pt), end: (80pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 176pt, dy: 104pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 84pt, line(
    start: (0pt, 0pt), end: (-40pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 56pt, dy: 104pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 70pt, dy: 10pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#e8f5e9"),
    stroke: (paint: rgb("#4caf50"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb0]),
  ))
  place(dx: 70pt, dy: 60pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#f3e5f5"),
    stroke: (paint: rgb("#9c27b0"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb1]),
  ))
  place(dx: 30pt, dy: 110pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#e3f2fd"),
    stroke: (paint: rgb("#2196f3"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb2]),
  ))
  place(dx: 150pt, dy: 110pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#ffebee"),
    stroke: (paint: rgb("#f44336"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb3]),
  ))
})

== Basic Blocks

=== bb0 #text(fill: rgb("#888888"), weight: "regular")[ — entry]

_Entry point of the function._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_2 = checked(-2 + 1)`], [Checked Add (may panic)],
  [`→ assert(move \_2.1 == false) → bb1`], [Panic if move \_2.1 is true],
)

=== bb1 #text(fill: rgb("#888888"), weight: "regular")[ — branch point]

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_1 = move \_2.0`], [Move value],
  [`\_4 = -1`], [Load constant],
  [`\_3 = move \_4 == \_1`], [Equal operation],
  [`→ switch(move \_3) \[0→bb3; else→bb2\]`], [Branch on move \_3],
)

=== bb2 #text(fill: rgb("#888888"), weight: "regular")[ — return / success]

_Normal return path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ return`], [Return from function],
)

=== bb3 #text(fill: rgb("#888888"), weight: "regular")[ — panic path]

_Panic/diverging path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ \_5 = panic(\[16 bytes\])`], [Call panic],
)

== Key Observations

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  #text(fill: rgb("#999999"))[TODO: Add bullet points summarizing what this MIR teaches]
  
  - 
  - 
]

== Takeaways

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  #text(fill: rgb("#999999"))[TODO: One or two sentences to generalize this example]
]

#pagebreak()

