// MIR Walkthrough - Generated by stable-mir-json

#set document(title: "MIR Walkthrough")
#set page(margin: 2cm, numbering: "1")
#set text(font: "New Computer Modern", size: 10pt)
#set heading(numbering: "1.1")
#set par(justify: true)

#show raw.where(block: true): block.with(
  fill: luma(245),
  inset: 8pt,
  radius: 4pt,
  width: 100%,
)

#show table.cell.where(y: 0): strong

= `main` — MIR Walkthrough

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  *Purpose:* #text(fill: rgb("#999999"))[TODO: Describe why this walkthrough exists]
]

== Source Context

```rust
fn main() {
    assert!(-128_i8 << 1 == 0);
    assert!(-32768_i16 << 1 == 0);
    assert!(-2147483648_i32 << 1 == 0);
    assert!(-9223372036854775808_i64 << 1 == 0);
    assert!(-170141183460469231731687303715884105728_i128 << 1 == 0);
}
```

== Function Overview

- *Function:* `main`
- *Basic blocks:* 16
- *Return type:* `()`
- *Notable properties:*
  - Contains panic path
  - Contains assertions
  - Has conditional branches

== Locals

#table(
  columns: (auto, 1fr, auto),
  align: (center, left, left),
  [*Local*], [*Type*], [*Notes*],
  [`0`], [`()`], [Return place],
  [`1`], [`i8`], [],
  [`2`], [`u32`], [],
  [`3`], [`bool`], [],
  [`4`], [`!`], [],
  [`5`], [`i16`], [],
  [`6`], [`u32`], [],
  [`7`], [`bool`], [],
  [`8`], [`!`], [],
  [`9`], [`i32`], [],
  [`10`], [`u32`], [],
  [`11`], [`bool`], [],
  [`12`], [`!`], [],
  [`13`], [`i64`], [],
  [`14`], [`u32`], [],
  [`15`], [`bool`], [],
  [`16`], [`!`], [],
  [`17`], [`i128`], [],
  [`18`], [`u32`], [],
  [`19`], [`bool`], [],
  [`20`], [`!`], [],
)

== Control-Flow Overview

#box(width: 230pt, height: 554pt, {
  place(dx: 100pt, dy: 34pt, line(
    start: (0pt, 0pt), end: (0pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 96pt, dy: 54pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 84pt, line(
    start: (0pt, 0pt), end: (-40pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 56pt, dy: 104pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 84pt, line(
    start: (0pt, 0pt), end: (80pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 176pt, dy: 104pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 60pt, dy: 134pt, line(
    start: (0pt, 0pt), end: (40pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 96pt, dy: 154pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 184pt, line(
    start: (0pt, 0pt), end: (-40pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 56pt, dy: 204pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 184pt, line(
    start: (0pt, 0pt), end: (80pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 176pt, dy: 204pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 60pt, dy: 234pt, line(
    start: (0pt, 0pt), end: (40pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 96pt, dy: 254pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 284pt, line(
    start: (0pt, 0pt), end: (-40pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 56pt, dy: 304pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 284pt, line(
    start: (0pt, 0pt), end: (80pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 176pt, dy: 304pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 60pt, dy: 334pt, line(
    start: (0pt, 0pt), end: (40pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 96pt, dy: 354pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 384pt, line(
    start: (0pt, 0pt), end: (-40pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 56pt, dy: 404pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 384pt, line(
    start: (0pt, 0pt), end: (80pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 176pt, dy: 404pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 60pt, dy: 434pt, line(
    start: (0pt, 0pt), end: (40pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 96pt, dy: 454pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 484pt, line(
    start: (0pt, 0pt), end: (-40pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 56pt, dy: 504pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 484pt, line(
    start: (0pt, 0pt), end: (80pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 176pt, dy: 504pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 70pt, dy: 10pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#e8f5e9"),
    stroke: (paint: rgb("#4caf50"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb0]),
  ))
  place(dx: 70pt, dy: 60pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#f3e5f5"),
    stroke: (paint: rgb("#9c27b0"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb1]),
  ))
  place(dx: 30pt, dy: 110pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#fafafa"),
    stroke: (paint: rgb("#9e9e9e"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb2]),
  ))
  place(dx: 150pt, dy: 110pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#ffebee"),
    stroke: (paint: rgb("#f44336"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb3]),
  ))
  place(dx: 70pt, dy: 160pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#f3e5f5"),
    stroke: (paint: rgb("#9c27b0"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb4]),
  ))
  place(dx: 30pt, dy: 210pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#fafafa"),
    stroke: (paint: rgb("#9e9e9e"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb5]),
  ))
  place(dx: 150pt, dy: 210pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#ffebee"),
    stroke: (paint: rgb("#f44336"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb6]),
  ))
  place(dx: 70pt, dy: 260pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#f3e5f5"),
    stroke: (paint: rgb("#9c27b0"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb7]),
  ))
  place(dx: 30pt, dy: 310pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#fafafa"),
    stroke: (paint: rgb("#9e9e9e"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb8]),
  ))
  place(dx: 150pt, dy: 310pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#ffebee"),
    stroke: (paint: rgb("#f44336"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb9]),
  ))
  place(dx: 70pt, dy: 360pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#f3e5f5"),
    stroke: (paint: rgb("#9c27b0"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb10]),
  ))
  place(dx: 30pt, dy: 410pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#fafafa"),
    stroke: (paint: rgb("#9e9e9e"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb11]),
  ))
  place(dx: 150pt, dy: 410pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#ffebee"),
    stroke: (paint: rgb("#f44336"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb12]),
  ))
  place(dx: 70pt, dy: 460pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#f3e5f5"),
    stroke: (paint: rgb("#9c27b0"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb13]),
  ))
  place(dx: 30pt, dy: 510pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#e3f2fd"),
    stroke: (paint: rgb("#2196f3"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb14]),
  ))
  place(dx: 150pt, dy: 510pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#ffebee"),
    stroke: (paint: rgb("#f44336"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb15]),
  ))
})

== Basic Blocks

=== bb0 #text(fill: rgb("#888888"), weight: "regular")[ — entry]

_Entry point of the function._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_2 = 1 as RigidTy(Uint(U32))`], [Integer conversion],
  [`\_3 = move \_2 \< 8`], [Less than operation],
  [`→ assert(move \_3 == true) → bb1`], [Panic if move \_3 is false],
)

=== bb1 #text(fill: rgb("#888888"), weight: "regular")[ — branch point]

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_1 = 128 \<\< 1`], [Shift left operation],
  [`→ switch(move \_1) \[0→bb2; else→bb3\]`], [Branch on move \_1],
)

=== bb2

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_6 = 1 as RigidTy(Uint(U32))`], [Integer conversion],
  [`\_7 = move \_6 \< 16`], [Less than operation],
  [`→ assert(move \_7 == true) → bb4`], [Panic if move \_7 is false],
)

=== bb3 #text(fill: rgb("#888888"), weight: "regular")[ — panic path]

_Panic/diverging path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ \_4 = panic(\[16 bytes\])`], [Call panic],
)

=== bb4 #text(fill: rgb("#888888"), weight: "regular")[ — branch point]

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_5 = -32768 \<\< 1`], [Shift left operation],
  [`→ switch(move \_5) \[0→bb5; else→bb6\]`], [Branch on move \_5],
)

=== bb5

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_10 = 1 as RigidTy(Uint(U32))`], [Integer conversion],
  [`\_11 = move \_10 \< 32`], [Less than operation],
  [`→ assert(move \_11 == true) → bb7`], [Panic if move \_11 is false],
)

=== bb6 #text(fill: rgb("#888888"), weight: "regular")[ — panic path]

_Panic/diverging path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ \_8 = panic(\[16 bytes\])`], [Call panic],
)

=== bb7 #text(fill: rgb("#888888"), weight: "regular")[ — branch point]

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_9 = -2147483648 \<\< 1`], [Shift left operation],
  [`→ switch(move \_9) \[0→bb8; else→bb9\]`], [Branch on move \_9],
)

=== bb8

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_14 = 1 as RigidTy(Uint(U32))`], [Integer conversion],
  [`\_15 = move \_14 \< 64`], [Less than operation],
  [`→ assert(move \_15 == true) → bb10`], [Panic if move \_15 is false],
)

=== bb9 #text(fill: rgb("#888888"), weight: "regular")[ — panic path]

_Panic/diverging path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ \_12 = panic(\[16 bytes\])`], [Call panic],
)

=== bb10 #text(fill: rgb("#888888"), weight: "regular")[ — branch point]

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_13 = -9223372036854775808 \<\< 1`], [Shift left operation],
  [`→ switch(move \_13) \[0→bb11; else→bb12\]`], [Branch on move \_13],
)

=== bb11

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_18 = 1 as RigidTy(Uint(U32))`], [Integer conversion],
  [`\_19 = move \_18 \< 128`], [Less than operation],
  [`→ assert(move \_19 == true) → bb13`], [Panic if move \_19 is false],
)

=== bb12 #text(fill: rgb("#888888"), weight: "regular")[ — panic path]

_Panic/diverging path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ \_16 = panic(\[16 bytes\])`], [Call panic],
)

=== bb13 #text(fill: rgb("#888888"), weight: "regular")[ — branch point]

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_17 = \[16 bytes\] \<\< 1`], [Shift left operation],
  [`→ switch(move \_17) \[0→bb14; else→bb15\]`], [Branch on move \_17],
)

=== bb14 #text(fill: rgb("#888888"), weight: "regular")[ — return / success]

_Normal return path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ return`], [Return from function],
)

=== bb15 #text(fill: rgb("#888888"), weight: "regular")[ — panic path]

_Panic/diverging path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ \_20 = panic(\[16 bytes\])`], [Call panic],
)

== Key Observations

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  #text(fill: rgb("#999999"))[TODO: Add bullet points summarizing what this MIR teaches]
  
  - 
  - 
]

== Takeaways

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  #text(fill: rgb("#999999"))[TODO: One or two sentences to generalize this example]
]

#pagebreak()

