// MIR Walkthrough - Generated by stable-mir-json

#set document(title: "MIR Walkthrough")
#set page(margin: 2cm, numbering: "1")
#set text(font: "New Computer Modern", size: 10pt)
#set heading(numbering: "1.1")
#set par(justify: true)

#show raw.where(block: true): block.with(
  fill: luma(245),
  inset: 8pt,
  radius: 4pt,
  width: 100%,
)

#show table.cell.where(y: 0): strong

= `main` — MIR Walkthrough

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  *Purpose:* #text(fill: rgb("#999999"))[TODO: Describe why this walkthrough exists]
]

== Source Context

```rust
fn main() {
    let a = 42;
    let mut b = &a;
    b = &b;
    
    assert!(*b == 42);
}
```

== Function Overview

- *Function:* `main`
- *Basic blocks:* 3
- *Return type:* `()`
- *Notable properties:*
  - Contains panic path
  - Introduces borrows
  - Has conditional branches

== Locals

#table(
  columns: (auto, 1fr, auto),
  align: (center, left, left),
  [*Local*], [*Type*], [*Notes*],
  [`0`], [`()`], [Return place],
  [`1`], [`i32`], [],
  [`2`], [`&i32`], [],
  [`3`], [`&&i32`], [],
  [`4`], [`i32`], [],
  [`5`], [`!`], [],
  [`6`], [`&i32`], [],
)

== Control-Flow Overview

#box(width: 230pt, height: 104pt, {
  place(dx: 100pt, dy: 34pt, line(
    start: (0pt, 0pt), end: (-40pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 56pt, dy: 54pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 34pt, line(
    start: (0pt, 0pt), end: (80pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 176pt, dy: 54pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 70pt, dy: 10pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#e8f5e9"),
    stroke: (paint: rgb("#4caf50"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb0]),
  ))
  place(dx: 30pt, dy: 60pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#e3f2fd"),
    stroke: (paint: rgb("#2196f3"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb1]),
  ))
  place(dx: 150pt, dy: 60pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#ffebee"),
    stroke: (paint: rgb("#f44336"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb2]),
  ))
})

== Basic Blocks

=== bb0 #text(fill: rgb("#888888"), weight: "regular")[ — entry]

_Entry point of the function._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_1 = 42`], [Load constant],
  [`\_2 = &\_1`], [Shared borrow],
  [`\_3 = &\_2`], [Shared borrow],
  [`\_6 = copy\_deref((\*\_3))`], [],
  [`\_2 = \_6`], [Copy value],
  [`\_4 = (\*\_2)`], [Copy value],
  [`→ switch(move \_4) \[42→bb1; else→bb2\]`], [Branch on move \_4],
)

=== bb1 #text(fill: rgb("#888888"), weight: "regular")[ — return / success]

_Normal return path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ return`], [Return from function],
)

=== bb2 #text(fill: rgb("#888888"), weight: "regular")[ — panic path]

_Panic/diverging path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ \_5 = panic(\[16 bytes\])`], [Call panic],
)

== Key Observations

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  #text(fill: rgb("#999999"))[TODO: Add bullet points summarizing what this MIR teaches]
  
  - 
  - 
]

== Takeaways

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  #text(fill: rgb("#999999"))[TODO: One or two sentences to generalize this example]
]

#pagebreak()

