// MIR Walkthrough - Generated by stable-mir-json

#set document(title: "MIR Walkthrough")
#set page(margin: 2cm, numbering: "1")
#set text(font: "New Computer Modern", size: 10pt)
#set heading(numbering: "1.1")
#set par(justify: true)

#show raw.where(block: true): block.with(
  fill: luma(245),
  inset: 8pt,
  radius: 4pt,
  width: 100%,
)

#show table.cell.where(y: 0): strong

= `main` — MIR Walkthrough

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  *Purpose:* #text(fill: rgb("#999999"))[TODO: Describe why this walkthrough exists]
]

== Source Context

```rust
fn main () {

    let mut a = MyStruct { a_value: 32, another: false, a_third: 32};

    // mutate field through ref and double-ref
    let r1 = &mut (a.a_value);
    *r1 = 42;
    assert!(a.a_value == 42);
    let mut r1 = &mut (a.a_value);
    let r2 = &mut r1;
    **r2 = 43;
    assert!(a.a_value == 43);

    // create reference-field chain
    let mut e = Enclosing{inner: &mut a};
    let ee = &mut e;

    // read and  write values through chain of ref/field projections
    let vv = (*(*ee).inner).a_value;
    assert!(vv == 43);

    (*(*ee).inner).another = true;

    let r3 = &mut (*ee).inner.a_third;
    *r3 = (*(*ee).inner).a_value as usize;

    assert!(a.another);
    assert!(a.a_third == 43);

}
```

== Function Overview

- *Function:* `main`
- *Basic blocks:* 11
- *Return type:* `()`
- *Notable properties:*
  - Contains panic path
  - Introduces borrows
  - Has conditional branches

== Locals

#table(
  columns: (auto, 1fr, auto),
  align: (center, left, left),
  [*Local*], [*Type*], [*Notes*],
  [`0`], [`()`], [Return place],
  [`1`], [`MyStruct`], [],
  [`2`], [`&mut i8`], [],
  [`3`], [`i8`], [],
  [`4`], [`!`], [],
  [`5`], [`&mut i8`], [],
  [`6`], [`&mut &mut i8`], [],
  [`7`], [`i8`], [],
  [`8`], [`!`], [],
  [`9`], [`Enclosing\<'\_\>`], [],
  [`10`], [`&mut MyStruct`], [],
  [`11`], [`&mut Enclosing\<'\_\>`], [],
  [`12`], [`i8`], [],
  [`13`], [`!`], [],
  [`14`], [`&mut usize`], [],
  [`15`], [`i8`], [],
  [`16`], [`bool`], [],
  [`17`], [`!`], [],
  [`18`], [`usize`], [],
  [`19`], [`!`], [],
  [`20`], [`&mut i8`], [],
  [`21`], [`&mut MyStruct`], [],
  [`22`], [`&mut MyStruct`], [],
  [`23`], [`&mut MyStruct`], [],
  [`24`], [`&mut MyStruct`], [],
)

== Control-Flow Overview

#box(width: 230pt, height: 304pt, {
  place(dx: 100pt, dy: 34pt, line(
    start: (0pt, 0pt), end: (-40pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 56pt, dy: 54pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 100pt, dy: 34pt, line(
    start: (0pt, 0pt), end: (80pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 176pt, dy: 54pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 60pt, dy: 84pt, line(
    start: (0pt, 0pt), end: (0pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 56pt, dy: 104pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 60pt, dy: 84pt, line(
    start: (0pt, 0pt), end: (120pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 176pt, dy: 104pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 60pt, dy: 134pt, line(
    start: (0pt, 0pt), end: (0pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 56pt, dy: 154pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 60pt, dy: 134pt, line(
    start: (0pt, 0pt), end: (120pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 176pt, dy: 154pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 60pt, dy: 184pt, line(
    start: (0pt, 0pt), end: (120pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 176pt, dy: 204pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 60pt, dy: 184pt, line(
    start: (0pt, 0pt), end: (0pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 56pt, dy: 204pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 60pt, dy: 234pt, line(
    start: (0pt, 0pt), end: (0pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 56pt, dy: 254pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 60pt, dy: 234pt, line(
    start: (0pt, 0pt), end: (120pt, 26pt),
    stroke: (paint: rgb("#666666"), thickness: 1pt),
  ))
  place(dx: 176pt, dy: 254pt, polygon(
    (0pt, 0pt), (4pt, 6pt), (8pt, 0pt),
    fill: rgb("#666666"),
  ))
  place(dx: 70pt, dy: 10pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#e8f5e9"),
    stroke: (paint: rgb("#4caf50"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb0]),
  ))
  place(dx: 30pt, dy: 60pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#f3e5f5"),
    stroke: (paint: rgb("#9c27b0"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb1]),
  ))
  place(dx: 150pt, dy: 60pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#ffebee"),
    stroke: (paint: rgb("#f44336"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb2]),
  ))
  place(dx: 30pt, dy: 110pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#f3e5f5"),
    stroke: (paint: rgb("#9c27b0"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb3]),
  ))
  place(dx: 150pt, dy: 110pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#ffebee"),
    stroke: (paint: rgb("#f44336"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb4]),
  ))
  place(dx: 30pt, dy: 160pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#f3e5f5"),
    stroke: (paint: rgb("#9c27b0"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb5]),
  ))
  place(dx: 150pt, dy: 160pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#ffebee"),
    stroke: (paint: rgb("#f44336"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb6]),
  ))
  place(dx: 30pt, dy: 210pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#f3e5f5"),
    stroke: (paint: rgb("#9c27b0"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb7]),
  ))
  place(dx: 150pt, dy: 210pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#ffebee"),
    stroke: (paint: rgb("#f44336"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb8]),
  ))
  place(dx: 30pt, dy: 260pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#e3f2fd"),
    stroke: (paint: rgb("#2196f3"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb9]),
  ))
  place(dx: 150pt, dy: 260pt, rect(
    width: 60pt, height: 24pt,
    fill: rgb("#ffebee"),
    stroke: (paint: rgb("#f44336"), thickness: 1pt),
    radius: 3pt,
    align(center + horizon, text(size: 9pt)[bb10]),
  ))
})

== Basic Blocks

=== bb0 #text(fill: rgb("#888888"), weight: "regular")[ — entry]

_Entry point of the function._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_1 = MyStruct(32, 0, 32)`], [Construct aggregate],
  [`\_2 = &mut \_1.0`], [Mutable borrow],
  [`(\*\_2) = 42`], [Load constant],
  [`\_3 = \_1.0`], [Copy value],
  [`→ switch(move \_3) \[42→bb1; else→bb2\]`], [Branch on move \_3],
)

=== bb1 #text(fill: rgb("#888888"), weight: "regular")[ — branch point]

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_5 = &mut \_1.0`], [Mutable borrow],
  [`\_6 = &mut \_5`], [Mutable borrow],
  [`\_20 = copy\_deref((\*\_6))`], [],
  [`(\*\_20) = 43`], [Load constant],
  [`\_7 = \_1.0`], [Copy value],
  [`→ switch(move \_7) \[43→bb3; else→bb4\]`], [Branch on move \_7],
)

=== bb2 #text(fill: rgb("#888888"), weight: "regular")[ — panic path]

_Panic/diverging path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ \_4 = panic(\[16 bytes\])`], [Call panic],
)

=== bb3 #text(fill: rgb("#888888"), weight: "regular")[ — branch point]

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_10 = &mut \_1`], [Mutable borrow],
  [`\_9 = Enclosing(\_10)`], [Construct aggregate],
  [`\_11 = &mut \_9`], [Mutable borrow],
  [`\_21 = copy\_deref((\*\_11).0)`], [],
  [`\_12 = (\*\_21).0`], [Copy value],
  [`→ switch(\_12) \[43→bb5; else→bb6\]`], [Branch on \_12],
)

=== bb4 #text(fill: rgb("#888888"), weight: "regular")[ — panic path]

_Panic/diverging path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ \_8 = panic(\[16 bytes\])`], [Call panic],
)

=== bb5 #text(fill: rgb("#888888"), weight: "regular")[ — branch point]

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_22 = copy\_deref((\*\_11).0)`], [],
  [`(\*\_22).1 = 1`], [Load constant],
  [`\_23 = copy\_deref((\*\_11).0)`], [],
  [`\_14 = &mut (\*\_23).2`], [Mutable borrow],
  [`\_24 = copy\_deref((\*\_11).0)`], [],
  [`\_15 = (\*\_24).0`], [Copy value],
  [`(\*\_14) = move \_15 as RigidTy(Uint(Usize))`], [Integer conversion],
  [`\_16 = \_1.1`], [Copy value],
  [`→ switch(move \_16) \[0→bb8; else→bb7\]`], [Branch on move \_16],
)

=== bb6 #text(fill: rgb("#888888"), weight: "regular")[ — panic path]

_Panic/diverging path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ \_13 = panic(\[16 bytes\])`], [Call panic],
)

=== bb7 #text(fill: rgb("#888888"), weight: "regular")[ — branch point]

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`\_18 = \_1.2`], [Copy value],
  [`→ switch(move \_18) \[43→bb9; else→bb10\]`], [Branch on move \_18],
)

=== bb8 #text(fill: rgb("#888888"), weight: "regular")[ — panic path]

_Panic/diverging path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ \_17 = panic(\[16 bytes\])`], [Call panic],
)

=== bb9 #text(fill: rgb("#888888"), weight: "regular")[ — return / success]

_Normal return path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ return`], [Return from function],
)

=== bb10 #text(fill: rgb("#888888"), weight: "regular")[ — panic path]

_Panic/diverging path._

#table(
  columns: (1fr, 1fr),
  align: (left, left),
  [*MIR*], [*Annotation*],
  [`→ \_19 = panic(\[16 bytes\])`], [Call panic],
)

== Key Observations

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  #text(fill: rgb("#999999"))[TODO: Add bullet points summarizing what this MIR teaches]
  
  - 
  - 
]

== Takeaways

#block(fill: luma(250), inset: 12pt, radius: 4pt, width: 100%)[
  #text(fill: rgb("#999999"))[TODO: One or two sentences to generalize this example]
]

#pagebreak()

