#!/usr/bin/env bash
# Generate index.html for MIR walkthrough pages
set -euo pipefail

outdir="${1:-.}"

cat > "$outdir/index.html" << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>stable-mir-json - MIR Walkthroughs</title>
    <style>
        :root {
            --bg: #1a1a2e;
            --bg-card: #16213e;
            --text: #eee;
            --text-dim: #888;
            --accent: #8be9fd;
            --green: #50fa7b;
            --purple: #bd93f9;
            --border: #333;
        }
        * { box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.6;
            margin: 0;
            padding: 2rem;
        }
        h1 { color: var(--accent); border-bottom: 2px solid var(--border); padding-bottom: 0.5rem; }
        .description { color: var(--text-dim); margin-bottom: 2rem; max-width: 800px; }
        .description a { color: var(--accent); }
        .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 1rem; }
        .card {
            background: var(--bg-card);
            border-radius: 8px;
            padding: 1rem 1.25rem;
            text-decoration: none;
            color: var(--text);
            transition: transform 0.15s, box-shadow 0.15s;
            border: 1px solid var(--border);
        }
        .card:hover { transform: translateY(-2px); box-shadow: 0 4px 12px rgba(0,0,0,0.3); border-color: var(--accent); }
        .card-title { color: var(--green); font-family: 'SF Mono', 'Fira Code', monospace; font-size: 1rem; margin: 0 0 0.5rem 0; }
        .card-links { display: flex; gap: 0.75rem; font-size: 0.85rem; }
        .card-links a { color: var(--text-dim); text-decoration: none; }
        .card-links a:hover { color: var(--accent); }
        .card-links .separator { color: var(--border); }
    </style>
</head>
<body>
    <h1>stable-mir-json</h1>
    <p class="description">
        Annotated MIR walkthroughs generated by <a href="https://github.com/runtimeverification/stable-mir-json">stable-mir-json</a>.<br>
        Each page shows: <strong>Source</strong> | <strong>Call Graph</strong> | <strong>MIR Walkthrough</strong>
    </p>
    <div class="grid">
EOF

# Add a card for each .smir.html file
for html in "$outdir"/*.smir.html; do
    [ -f "$html" ] || continue
    name=$(basename "$html" .smir.html)
    svg="${outdir}/${name}.smir.svg"
    if [ -f "$svg" ]; then
        echo "        <div class=\"card\"><div class=\"card-title\">${name}</div><div class=\"card-links\"><a href=\"${name}.smir.html\">HTML</a><span class=\"separator\">|</span><a href=\"${name}.smir.svg\">SVG</a></div></div>" >> "$outdir/index.html"
    else
        echo "        <div class=\"card\"><div class=\"card-title\">${name}</div><div class=\"card-links\"><a href=\"${name}.smir.html\">HTML</a></div></div>" >> "$outdir/index.html"
    fi
done

# Add a card for each .wasm-explore.html file
for html in "$outdir"/*.wasm-explore.html; do
    [ -f "$html" ] || continue
    name=$(basename "$html" .wasm-explore.html)
    echo "        <a class=\"card\" href=\"${name}.wasm-explore.html\"><div class=\"card-title\">${name} (wasm)</div></a>" >> "$outdir/index.html"
done

cat >> "$outdir/index.html" << 'EOF'
    </div>
</body>
</html>
EOF
